In [3]:
import numpy as np


In [4]:
a=np.array([5,6,7])

In [4]:
a

array([5, 6, 7])

In [5]:
a[0]

5

In [7]:
type(a)

numpy.ndarray

In [12]:
a=np.array([[5,6,7] ,[8,9,10]])

In [13]:
a

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [16]:
a.shape

(2L, 3L)

In [20]:
a.ndim# distionmof arry

2

In [22]:
a.itemsize # byte size

4

In [2]:
a.dtype

NameError: name 'a' is not defined

In [1]:
a=np.array([[1,2],[3,4],[5,6]],dtype=float)

NameError: name 'np' is not defined

In [27]:
a.itemsize

8

In [28]:
a.dtype

dtype('float64')

In [29]:
a # only numpy consider as a intergier

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [30]:
a.size# total element


6

In [31]:
a.reshape(2,3)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [34]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
l=range(5)

In [37]:
l

[0, 1, 2, 3, 4]

In [38]:
np.arange(1,5)

array([1, 2, 3, 4])

In [39]:
np.arange(1,5,2)#0,,1,2,3,4,5

array([1, 3])

In [40]:
np.linspace(1,5,8)

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

In [41]:
a=np.array([[1,2],[4,5],[6,7]])

In [42]:
a.sum()

25

In [43]:
a.min()

1

In [44]:
a.max()

7

In [45]:
a.std()

2.1147629234082532

In [47]:
a

array([[1, 2],
       [4, 5],
       [6, 7]])

In [46]:
a.sum(axis=0)#sum of c

array([11, 14])

In [49]:
a.sum(axis=1)#r

array([ 3,  9, 13])

In [50]:
a=np.array([[1,2],[3,4]])


In [51]:
a

array([[1, 2],
       [3, 4]])

In [52]:
b=np.array([[3,2],[5,4]])


In [53]:
a+b

array([[4, 4],
       [8, 8]])

In [54]:
a-b

array([[-2,  0],
       [-2,  0]])

In [55]:
a/b

array([[0, 1],
       [0, 1]])

In [56]:
a*b

array([[ 3,  4],
       [15, 16]])

In [58]:
a.dot(b)# matrix multipltion

array([[13, 10],
       [29, 22]])

In [5]:
import numpy as np

In [6]:
d=np.array([1,2,3])

In [7]:
d

array([1, 2, 3])

In [8]:
d1=np.array(range(10))

In [9]:
d1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
print type(d1)

<type 'numpy.ndarray'>


In [15]:
d2=np.array([[5,6,7] ,[8,9,10]])

In [16]:
d2

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [17]:
print type(d1)

<type 'numpy.ndarray'>


In [20]:
d2.shape

(2L, 3L)

In [22]:
d2.dtype

dtype('int32')

In [23]:
d2.ndim

2

In [24]:
d2.itemsize

4

In [25]:
d2.reshape(3,2)

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [27]:
d3=np.array([[10,11,10],[13,14,15],[16,17,18]])

In [28]:
d3

array([[10, 11, 10],
       [13, 14, 15],
       [16, 17, 18]])

In [32]:
d3[1,2]
# c,r

15

In [30]:
d3[2,2]

18

In [31]:
d3[0:2,1]

array([11, 14])

In [34]:
   #0  1   2
#0 [10,11,10
#1   13,14,15
 # 2  16,17,18]

In [35]:
d3[0:3,0:2]

array([[10, 11],
       [13, 14],
       [16, 17]])

In [38]:
for i in d3:
    print i

[10 11 10]
[13 14 15]
[16 17 18]


In [39]:
for i in d3.flat:
    print i

10
11
10
13
14
15
16
17
18


In [45]:
d3=np.arange (6).reshape(3,2)

In [46]:
d3

array([[0, 1],
       [2, 3],
       [4, 5]])

In [47]:
d4=np.arange(6,12).reshape(3,2)

In [48]:
d4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [51]:
np.vstack((d3,d4))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [53]:
np.hstack((d3,d4))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [54]:
d4=np.arange(30).reshape(2,15)

In [55]:
d4

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [61]:
rest=np.vsplit(d4,2)

In [62]:
rest

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [63]:
rest[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [64]:
rest[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [65]:
rest[2]

IndexError: list index out of range

In [67]:
itr=iter([10,20])

In [68]:
itr

In [70]:
next(itr)

10

In [76]:
g=lambda x:x*x
g(10)

100

In [81]:
l=[40,50,85]
a=filter(lambda x:x%2==0,l) #list

In [82]:
a

[40, 50]

In [83]:
map(lambda x:x+10,l)# map  list 

[50, 60, 95]